src/Entity/Bills.php
<?php

namespace App\Entity;

use App\Repository\BillsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BillsRepository::class)]
class Bills
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date = null;

    #[ORM\Column]
    private ?float $total_price = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?bool $status = null;

    #[ORM\ManyToOne(targetEntity: Users::class, inversedBy: 'bills')]
    #[ORM\JoinColumn(nullable: false)]
    private ?users $user = null;

    #[ORM\OneToMany(targetEntity: ReservationsEvents::class, mappedBy: 'bill')]
    private Collection $reservationsEvents;

    #[ORM\OneToMany(targetEntity: ReservationsRentals::class, mappedBy: 'bill')]
    private Collection $reservationsRentals;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $paymentIntentId = null;

    public function __construct()
    {
        $this->reservationsEvents = new ArrayCollection();
        $this->reservationsRentals = new ArrayCollection();
    }

    public function getReservationsEvents(): Collection
    {
        return $this->reservationsEvents;
    }

    public function setReservationsEvents(Collection $reservationsEvents): void
    {
        $this->reservationsEvents = $reservationsEvents;
    }

    public function getReservationsRentals(): Collection
    {
        return $this->reservationsRentals;
    }

    public function setReservationsRentals(Collection $reservationsRentals): void
    {
        $this->reservationsRentals = $reservationsRentals;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(\DateTimeImmutable $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->total_price;
    }

    public function setTotalPrice(float $total_price): static
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getUser(): ?users
    {
        return $this->user;
    }

    public function setUser(?users $user): static
    {
        $this->user = $user;

        return $this;
    }
    public function getAllReservations(): array
    {
        return array_merge(
            $this->reservationsEvents->toArray(),
            $this->reservationsRentals->toArray()
        );
    }

    public function getPaymentIntentId(): ?string
    {
        return $this->paymentIntentId;
    }

    public function setPaymentIntentId(?string $paymentIntentId): static
    {
        $this->paymentIntentId = $paymentIntentId;

        return $this;
    }
}

src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    /**
     * @var Collection<int, Images>
     */
    #[ORM\OneToMany(targetEntity: Images::class, mappedBy: 'posts')]
    private Collection $Images;

    public function __construct()
    {
        $this->Images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getUserId(): ?Users
    {
        return $this->user;
    }

    public function setUserId(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->Images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->Images->contains($image)) {
            $this->Images->add($image);
            $image->setPosts($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->Images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getPosts() === $this) {
                $image->setPosts(null);
            }
        }

        return $this;
    }
    public function getHomePageImage(): Images | null
    {
        foreach ($this->getImages() as $image) {
            if ($image->isHomePage() === true) {
                return $image;
            }
        }

        return null;
    }

    public function setHomeImage(Images $newImage): void
    {
        if($this->getHomePageImage()){
            $this->getHomePageImage()->setSrc($newImage->getSrc());
            $this->getHomePageImage()->setAlt($newImage->getAlt());
            $this->getHomePageImage()->setSrc($newImage->getSrc());
        }
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastname = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $last_log_at = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\Column]
    private ?bool $is_email_authentificated = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Images $image = null;

    /**
     * @var Collection<int, Bills>
     */
    #[ORM\OneToMany(targetEntity: Bills::class, mappedBy: 'user')]
    private Collection $bills;

    /**
     * @var Collection<int, ReservationsEvents>
     */
    #[ORM\OneToMany(targetEntity: ReservationsEvents::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $reservationsEvents;

    /**
     * @var Collection<int, ReservationsRentals>
     */
    #[ORM\OneToMany(targetEntity: ReservationsRentals::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $reservationsRentals;


    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $birth_date = null;

    /**
     * @var Collection<int, Comments>
     */
    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $comments;

    private ?string $googleAuthenticatorSecret = null;

    public function isGoogleAuthenticatorEnabled(): bool
    {
        return null !== $this->googleAuthenticatorSecret;
    }

    public function getGoogleAuthenticatorSecret(): ?string
    {
        return $this->googleAuthenticatorSecret;
    }

    public function setGoogleAuthenticatorSecret(?string $secret): void
    {
        $this->googleAuthenticatorSecret = $secret;
    }

    public function __construct()
    {
        $this->bills = new ArrayCollection();
        $this->reservationsEvents = new ArrayCollection();
        $this->reservationsRentals = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): static
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getImage(): ?images
    {
        return $this->image;
    }

    public function setImage(images $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getLastLogAt(): ?\DateTimeImmutable
    {
        return $this->last_log_at;
    }

    public function setLastLogAt(\DateTimeImmutable $last_log_at): static
    {
        $this->last_log_at = $last_log_at;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function isEmailAuthentificated(): ?bool
    {
        return $this->is_email_authentificated;
    }

    public function setIsEmailAuthentificated(bool $is_email_authentificated): static
    {
        $this->is_email_authentificated = $is_email_authentificated;

        return $this;
    }

    /**
     * @return Collection<int, Bills>
     */
    public function getBills(): Collection
    {
        return $this->bills;
    }

    public function addBill(Bills $bill): static
    {
        if (!$this->bills->contains($bill)) {
            $this->bills->add($bill);
            $bill->setUser($this);
        }

        return $this;
    }

    public function removeBill(Bills $bill): static
    {
        if ($this->bills->removeElement($bill)) {
            // set the owning side to null (unless already changed)
            if ($bill->getUser() === $this) {
                $bill->setUser(null);
            }
        }

        return $this;
    }

    public function getBirthDate(): ?\DateTimeImmutable
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeImmutable $birth_date): static
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return Collection<int, ReservationsEvents>
     */
    public function getReservationsEvents(): Collection
    {
        return $this->reservationsEvents;
    }

    public function addReservationsEvent(ReservationsEvents $reservationEvent): static
    {
        if (!$this->reservationsEvents->contains($reservationEvent)) {
            $this->reservationsEvents->add($reservationEvent);
            $reservationEvent->setUser($this);
        }

        return $this;
    }

    public function removeReservationsEvent(ReservationsEvents $reservationEvent): static
    {
        if ($this->reservationsEvents->removeElement($reservationEvent)) {
            if ($reservationEvent->getUser() === $this) {
                $reservationEvent->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ReservationsRentals>
     */
    public function getReservationsRentals(): Collection
    {
        return $this->reservationsRentals;
    }

    public function addReservationsRental(ReservationsRentals $reservationRental): static
    {
        if (!$this->reservationsRentals->contains($reservationRental)) {
            $this->reservationsRentals->add($reservationRental);
            $reservationRental->setUser($this);
        }

        return $this;
    }

    public function removeReservationsRental(ReservationsRentals $reservationRental): static
    {
        if ($this->reservationsRentals->removeElement($reservationRental)) {
            if ($reservationRental->getUser() === $this) {
                $reservationRental->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

}

templates/pdf/bill.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Facture #{{ bill.id }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header, .footer { text-align: center; }
        .table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .table th, .table td { border: 1px solid #000; padding: 6px; }
        td, .titleReservations{text-align: center;}
    </style>
</head>
<body>
<div class="header">
    <h2>Domaine du Soleil</h2>
    <p>35 Rue du Soleil, 5000 Namur, Belgique</p>
    <p>TVA : BE0123.456.789</p>
</div>

<h3>Facture n°{{ bill.id }}</h3>
<p><strong>Date :</strong> {{ bill.date|date('d/m/Y') }}</p>
<p><strong>Client :</strong> {{ user.firstname }} {{ user.lastname }} - {{ user.email }}</p>

{% if rentals|length > 0 %}
    <h3 class="titleReservations">Locations</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Description</th>
            <th>Date de début</th>
            <th>Date de fin</th>
            <th>TVA</th>
            <th>Prix HT</th>
            <th>TVA</th>
            <th>Caution</th>
            <th>Frais</th>
            <th>Total TTC</th>
        </tr>
        </thead>
        <tbody>
            {% for rental in rentals %}
                <tr>
                    <td>{{ rental.rentals.id }}</td>
                    <td>{{ rental.rentals.title|capitalize }}</td>
                    <td>{{ rental.dateStart|date('d/m/Y') }}</td>
                    <td>{{ rental.dateEnd|date('d/m/Y') }}</td>
                    <td>10%</td>
                    <td>{{ (rental.totalPrice / 1.10)|number_format(2, ',', '.') }}€</td>
                    <td>{{ (rental.totalPrice - (rental.totalPrice / 1.10))|number_format(2, ',', '.') }}€</td>
                    <th>{{ (rental.rentals.pricePerDay * 2)|number_format(2, ',', '.') }}€</th>
                    <th>50€</th>
                    <td>{{ rental.totalPrice|number_format(2, ',', '.') }}€</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}


{% if events|length > 0 %}
    <h3 class="titleReservations">Événements</h3>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Description</th>
            <th>Nombre de places</th>
            <th>TVA</th>
            <th>Prix HT</th>
            <th>TVA</th>
            <th>Total TTC</th>
        </tr>
        </thead>
        <tbody>
        {% for events in events %}
            <tr>
                <td>{{ events.event.id }}</td>
                <td>{{ events.event.title|capitalize }}</td>
                <td>{{ events.nbPlaces }}</td>
                <td>20%</td>
                <td>{{ (events.totalDeposit / 1.10)|number_format(2, ',', '.') }}€</td>
                <td>{{ (events.totalDeposit - (events.totalDeposit / 1.10))|number_format(2, ',', '.') }}€</td>
                <td>{{ events.totalDeposit|number_format(2, ',', '.') }}€</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}

<h3>Total TTC : {{ bill.totalPrice|number_format(2, ',', '.') }}€</h3>

<div class="footer">
    <p>Merci pour votre réservation !</p>
</div>
</body>
</html>

templates/pdf/user.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>User Info</title>
    <style>
        body { font-family: Arial, sans-serif; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        td, th { border: 1px solid #ccc; padding: 8px; text-align: left; }
    </style>
</head>
<body>
<h1>Données de {{ user.firstname|capitalize }} {{ user.lastname|capitalize }}</h1>
<table>
    <tr><th>ID</th><td>{{ user.id }}</td></tr>
    <tr><th>Email</th><td>{{ user.email }}</td></tr>
    <tr><th>Prénom</th><td>{{ user.firstname }}</td></tr>
    <tr><th>Nom</th><td>{{ user.lastname ?? 'N/A' }}</td></tr>
    <tr><th>Date de naissance</th><td>{{ user.birthDate ? user.birthDate.format('d/m/Y') : 'N/A' }}</td></tr>
    <tr><th>Date de création</th><td>{{ user.createdAt.format('d/m/Y H:i') }}</td></tr>
    <tr><th>Dernière connexion</th><td>{{ user.lastLogAt.format('d/m/Y H:i') }}</td></tr>
    <tr><th>Compte actif</th><td>{{ user.isActive ? 'Oui' : 'Non' }}</td></tr>
    <tr><th>Email vérifié</th><td>{{ user.isEmailAuthentificated ? 'Oui' : 'Non' }}</td></tr>
    <tr><th>Rôles</th><td>{{ user.roles|join(', ') }}</td></tr>
</table>
</body>
</html>