src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date = null;

    #[ORM\Column]
    private ?int $nb_places = null;

    #[ORM\Column]
    private ?bool $is_active = null;

    #[ORM\Column]
    private ?int $age_requirement = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    /**
     * @var Collection<int, Images>
     */
    #[ORM\OneToMany(targetEntity: Images::class, mappedBy: 'events')]
    private Collection $images;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    /**
     * @var Collection<int, ReservationsEvents>
     */
    #[ORM\OneToMany(targetEntity: ReservationsEvents::class, mappedBy: 'event')]
    private Collection $reservations;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function setReservations(Collection $reservations): void
    {
        $this->reservations = $reservations;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(\DateTimeImmutable $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getNbPlaces(): ?int
    {
        return $this->nb_places;
    }

    public function setNbPlaces(int $nb_places): static
    {
        $this->nb_places = $nb_places;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getAgeRequirement(): ?int
    {
        return $this->age_requirement;
    }

    public function setAgeRequirement(int $age_requirement): static
    {
        $this->age_requirement = $age_requirement;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setEvents($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getEvents() === $this) {
                $image->setEvents(null);
            }
        }

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function isPast(): bool
    {
        $now = new \DateTimeImmutable();
        return $this->date < $now;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }
    public function getHomePageImage(): Images | null
    {
        foreach ($this->getImages() as $image) {
            if ($image->isHomePage() === true) {
                return $image;
            }
        }

        return null;
    }

    public function getRemainingPlaces(): int
    {
        $reservedPlaces = 0;
        foreach ($this->reservations as $reservation) {
            $reservedPlaces += $reservation->getNbPlaces();
        }

        return $this->nb_places - $reservedPlaces;
    }

    public function setHomeImage(Images $newImage): void
    {
        if($this->getHomePageImage()){
            $this->getHomePageImage()->setSrc($newImage->getSrc());
            $this->getHomePageImage()->setAlt($newImage->getAlt());
            $this->getHomePageImage()->setSrc($newImage->getSrc());
        }
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextareaType::class, [
                'label' => 'Titre',
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'Le titre ne peut pas être vide.',
                    ]),
                    new Assert\Length([
                        'min' => 5,
                        'minMessage' => 'Le titre doit faire au moins {{ limit }} caractères.',
                    ]),
                ],
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Description',
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'La description ne peut pas être vide.',
                    ]),
                    new Assert\Length([
                        'min' => 10,
                        'minMessage' => 'La description doit faire au moins {{ limit }} caractères.',
                    ]),
                ],
            ])
            ->add('price', MoneyType::class, [
                'currency' => 'EUR',
                'constraints' => [
                    new Assert\NotNull([
                        'message' => 'Le prix est requis.',
                    ]),
                    new Assert\GreaterThanOrEqual([
                        'value' => 0,
                        'message' => 'Le prix ne peut pas être négatif.',
                    ]),
                ],
            ])
            ->add('date', DateType::class, [
                'widget' => 'single_text',
                'constraints' => [
                    new Assert\NotNull([
                        'message' => 'La date est requise.',
                    ]),
                    new Assert\GreaterThanOrEqual([
                        'value' => 'today',
                        'message' => 'La date ne peut pas être dans le passé.',
                    ]),
                ],
            ])
            ->add('nb_places', IntegerType::class, [
                'label' => 'Nombre de places',
                'constraints' => [
                    new Assert\NotNull([
                        'message' => 'Le nombre de places est requis.',
                    ]),
                    new Assert\Positive([
                        'message' => 'Le nombre de places doit être supérieur à zéro.',
                    ]),
                ],
            ])
            ->add('location', TextType::class, [
                'label' => 'Lieu',
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => 'Le lieu est requis.',
                    ]),
                    new Assert\Length([
                        'min' => 3,
                        'minMessage' => 'Le lieu doit contenir au moins {{ limit }} caractères.',
                    ]),
                ],
            ])
            ->add('is_active', CheckboxType::class, [
                'label'    => 'Actif',
                'required' => false,
            ])
            ->add('age_requirement', IntegerType::class, [
                'label' => 'Âge requis',
                'constraints' => [
                    new Assert\NotNull([
                        'message' => 'L’âge requis est obligatoire.',
                    ]),
                    new Assert\GreaterThanOrEqual([
                        'value' => 0,
                        'message' => 'L’âge requis doit être positif.',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\ReservationsEvents;
use App\Form\ReservationsEventsType;
use App\Repository\EventsRepository;
use App\Repository\ReservationsEventsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Attribute\Route;

final class EventController extends AbstractController
{
    #[Route('/events', name: 'app_events')]
    public function index(EventsRepository $eventsRepository): Response
    {
        return $this->render('events/index.html.twig', [
            'events' => $eventsRepository->findActiveEvents(),
        ]);
    }
    #[Route('/event/{id}', name: 'app_event')]
    public function event($id, SessionInterface $session, EventsRepository $eventsRepository, Request $request, ReservationsEventsRepository $reservationsEventsRepository): Response
    {
        $event = $eventsRepository->find($id);

        $user = $this->getUser();
        $reservationUser = 0;
        $totalPlaceCart = 0;

        if($user){
            $reservationUser = $reservationsEventsRepository->getTotalPlacesByUserAndEvent($user->getId(), $event->getId());
        }

        $cart = $session->get('myCart', []);

        foreach ($cart as $elemCart) {
            if (
                $elemCart['type'] === 'event' &&
                isset($elemCart['eventId']) &&
                $elemCart['eventId'] === $event->getId()
            ) {
                $totalPlaceCart += $elemCart['nbPlaces'];
            }
        }

        $reservationUser = $totalPlaceCart + $reservationUser;

        $reservation = new ReservationsEvents();
        $reservation->setEvent($event);

        $form = $this->createForm(ReservationsEventsType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && $event->isActive()) {
            if($event->isPast()){
                $this->addFlash('danger', 'Événement déjà passé.');
                return $this->render('event/index.html.twig', [
                    'event' => $event,
                    'form' => $form->createView(),
                ]);
            }

            $totalReservationUser = $reservation->getNbPlaces() + $reservationUser;

            if ($totalReservationUser > 20) {
                $this->addFlash('danger', 'Vous ne pouvez pas avoir plus de 20 places pour cet événement !');
                return $this->render('event/index.html.twig', [
                    'event' => $event,
                    'form' => $form->createView(),
                    'maxReservations' => $reservationUser,
                ]);
            }

            if($reservation->getNbPlaces() > $event->getRemainingPlaces()){
                $this->addFlash('danger', 'Pas assez de places pour la demande.');
                return $this->render('event/index.html.twig', [
                    'event' => $event,
                    'form' => $form->createView(),
                    'maxReservations' => $reservationUser,
                ]);
            }
            $session->set('newReservationEvent', [
                'eventId' => $event->getId(),
                'type' => 'event',
                'image' => $event->getHomePageImage(),
                'nbPlaces' => $reservation->getNbPlaces(),
            ]);

            return $this->redirectToRoute('app_cart');
        }

        return $this->render('event/index.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
            'maxReservations' => $reservationUser,
        ]);
    }
}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les événements{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('libs/jquery/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ asset('libs/magnific-popup/dist/jquery.magnific-popup.min.js') }}"></script>
    <script src="{{ asset('js/events.js') }}"></script>
{% endblock %}

{% block body %}
    <header class="bg-darkGreen contentMargin d-flex justify-content-center flex-column align-items-center pb-4">
        <h2 class="text-center color-white">Tous les événements</h2>
        <div class="mt-5 w-75">
            <div class="row justify-content-center">
                {% for event in events %}
                    <div class="eventsItem d-none col-12 col-xl-6 mb-4 px-3 d-flex flex-column">
                        <div class="d-md-none d-flex">
                            <img src="{{ asset('uploads/' ~ event.getHomePageImage().src) }}" class=" rounded-4 object-fit-cover imageEvents w-100 object-fit-cover" alt="{{ asset('uploads/' ~ event.getHomePageImage().alt) }}">
                        </div>
                        <div class="card event-card w-100 h-100 border-0 rounded-4 d-flex flex-column flex-xl-row">
                            <div class="container row g-0 h-100">
                                <div class="col-md-5 col-1 h-100">
                                    <img src="{{ asset('uploads/' ~ event.getHomePageImage().src) }}" class="d-none d-md-flex object-fit-cover rounded-start-4 w-100 h-100" alt="{{ asset('uploads/' ~ event.getHomePageImage().alt) }}">
                                </div>
                                <div class="col-md-7 col-10 d-flex flex-column">
                                    <div class="card-body d-flex flex-column">
                                        <h4 class="card-title">
                                            <a href="{{ path('app_event', {id:event.id}) }}" class="text-decoration-none color-darkGreen">
                                                {{ event.title|slice(0, 25)|join(' ') ~ '...' }}
                                            </a>
                                        </h4>

                                        <ul class="d-flex flex-column list-unstyled gap-1">
                                            <li>
                                                {% if event.ageRequirement == 0 %}
                                                    <span class="fw-bold">Pour tout le monde !</span>
                                                {% else %}
                                                    À partir de <span class="fw-bold">{{ event.ageRequirement }} ans</span>
                                                {% endif %}
                                            </li>
                                            <li>
                                                <img src="{{ asset('styles/img/location.svg') }}" alt="Location de l'événement">
                                                {{ event.location }}
                                            </li>
                                            <li>
                                                <img src="{{ asset('styles/img/calendar.svg') }}" alt="Date de l'événement">
                                                le {{ event.date|date('d/m/Y') }}
                                                {% if event.isPast() %}
                                                    <span class="color-red fw-bold"> (Événement déjà passé)</span>
                                                {% endif %}
                                            </li>
                                            <li>
                                                {{ event.nbPlaces }} places
                                                <span class="color-darkGreen fw-bold">
                                                    {% if not event.isPast() %}
                                                        {% if event.getRemainingPlaces() <= 0 %}
                                                            <span class="color-red">(Complet !)</span>
                                                        {% else %}
                                                            ({{ event.getRemainingPlaces() }} places restantes)
                                                        {% endif %}
                                                    {% endif %}
                                                </span>
                                            </li>
                                        </ul>
                                        <div class="mt-auto">
                                            <div class="d-flex justify-content-between align-items-center">
                                                <a href="{{ path('app_event', {id:event.id}) }}" class="btn-yellow">Voir plus</a>
                                                <span class="price h3">{{ event.price|number_format(2, ',', '') }}€/pers</span>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <button class="btn-yellow voir-plus">Voir plus...</button>
    </header>
{% endblock %}